import React from "react";
import Image from "next/image";
import Link from "next/link";
import { GoLinkExternal } from "react-icons/go";

const dynamicApps = [
  {
    link: "https://my-exams-ramkumargurav.vercel.app",
    name: "MyExams.com",
    image: "/myexams2.png",
    desc: "It's an education related app where one can take tests , browse and search mcqs, download notes and also buy books using stripe payment interface",
  },
  {
    link: "https://myblogs-ramkumargurav.vercel.app",
    name: "MyBlogs.com",
    image: "/myblogs1.png",
    desc: "It's a blogging related app where you can see blog posts of others and also you can create an account and Post your own blog posts",
  },
  {
    link: "https://royal-villas-ramkumargurav.vercel.app",
    name: "RoyalVillas.com",
    image: "/royalvillas2.png",
    desc: "It's an app related to hotel bookings where one can make advance reservations for rooms and also can buy villa party packages using stripe payment interface",
  },
];

const staticApps = [
  {
    link: "https://ramkumargurav.github.io/Tindog",
    name: "Tindog.com",
    image: "/tindog1.png",
    desc: "It's a social media app for dogs so they can meet new dogs and find their true love",
  },
  {
    link: "https://ramkumargurav.github.io/My-Portfolio",
    name: "Portfolio.com",
    image: "/portfolio1.png",
    desc: "It's a portfolio app for web developers ",
  },
  {
    link: "https://ramkumargurav.github.io/Get-Weather",
    name: "GetWeather.com",
    image: "/getweather1.png",
    desc: "It's an app where we can search for weather details of various cities  ",
  },
  {
    link: "https://ramkumargurav.github.io/Simon-Game",
    name: "SimonGame.com",
    image: "/simongame1.png",
    desc: "It's a popular simon game where one must remember the previously displayed colors",
  },
  {
    link: "https://ramkumargurav.github.io/Dice-Game/",
    name: "DiceRollGame.com",
    image: "/dicegame1.png",
    desc: "It's a 2 player game of dices where one wins if he get higher score than other one",
  },
  {
    link: "https://ramkumargurav.github.io/guess-it-game",
    name: "NumberGuessGame.com",
    image: "/numberguessgame1.png",
    desc: "It's a game about guessing the hidden number generated by computer",
  },
  {
    link: "https://jagadishgulaguntimla-ramkumargurav.vercel.app",
    name: "jagadishgulaguntimla.com",
    image: "/mla_homepage.png",
    desc: "It's a portfolio web application for a politician and where you can submit your complaints  ",
  },
];

const springbootApis = [
  {
    link: "https://talented-ant-loincloth.cyclic.app/api/v1/posts",
    name: "myblogs.com/api/v1/villa-reservations",
    image: "/apiImg5.png",
    desc: "It's an API for blogs website using MongoDB Database and built using Nodejs",
  },
  {
    link: "https://talented-ant-loincloth.cyclic.app/api/v1/questions",
    name: "myexams.com/api/v1/posts/all",
    image: "/apiImg5.png",
    desc: "It's an API for educational webstie using MongoDB Database and built using Nodejs",
  },
  {
    link: "https://talented-ant-loincloth.cyclic.app/api/v1/villa-reservations",
    name: "villas.com/api/v1/villa-reservations",
    image: "/apiImg5.png",
    desc: "It's an API for educational webstie using MongoDB Database and built using Nodejs",
  },
  {
    link: "https://test-sm-blogs-api.onrender.com/api/v1/swagger-ui/index.html",
    name: "rblogs.com/api/v1",
    image: "/apiImg5.png",
    desc: "It's an API for Blogs website using MongoDB Database and built using Springboot framework",
  },
];
const Projects = () => {
  return (
    <div id="projects" className="py-4">
      <h1 className="text-4xl text-white font-semibold  sm:text-[60px] mb-10 px-10 my-4">
        My Projects
      </h1>

      <h2 className="rounded-md my-4 mx-10 py-4 pl-4 mt-10 text-xl font-semibold nunito uppercase  sm:text-[30px] text-white bg-[#8a8888]">
        {dynamicApps.length} Dynamic Websites <br />
      </h2>
      <p className="pl-16 my-4 text-base text-white  sm:text-[20px]  ">
        {" "}
        Built thier Frontend using Reactjs and Backend using Nodejs
      </p>
      <section className="mb-20">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 px-10 py-4 place-content-center place-items-center">
          {dynamicApps.map((app, i) => (
            <div
              key={i}
              className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden"
            >
              <Image
                src={`${app.image}`}
                alt="profile"
                fill
                sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
                priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
                className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
              />
              <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
                <Link href={`${app.link}`} className="text-xl text-white ">
                  {app.name}
                </Link>
                <p className="text-sm text-white px-2 text-center ">
                  {app.desc}
                </p>
                <Link
                  href={`${app.link}`}
                  className="rounded-full p-4 bg-white"
                >
                  <GoLinkExternal size={25} className="col-primary" />
                </Link>
              </div>
            </div>
          ))}
          {/* <div className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden">
            <Image
              src={"/myexams2.png"}
              alt="profile"
              fill
              sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
              priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
              className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
            />
            <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
              <Link
                href={"https://my-exams-ramkumargurav.vercel.app"}
                className="text-xl text-white"
              >
                MyExams.com
              </Link>
              <p className="text-sm text-white px-2 text-center ">
                It's an education related app where one can take tests , browse
                and search mcqs, download notes and also buy books with payment
                interface{" "}
              </p>
              <Link
                href={"https://my-exams-ramkumargurav.vercel.app"}
                className="rounded-full p-4 bg-white"
              >
                <GoLinkExternal size={25} className="col-primary" />
              </Link>
            </div>
          </div>
          <div className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden">
            <Image
              src={"/myblogs1.png"}
              alt="profile"
              fill
              sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
              priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
              className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
            />
            <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
              <Link
                href={"https://myblogs-ramkumargurav.vercel.app"}
                className="text-xl text-white"
              >
                MyBlogs.com
              </Link>
              <p className="text-sm text-white px-2 text-center ">
                It's a blogging related app where you can see blog posts of
                others and also you can create an account and Post your own
                blogs
              </p>
              <Link
                href={"https://myblogs-ramkumargurav.vercel.app"}
                className="rounded-full p-4 bg-white"
              >
                <GoLinkExternal size={25} className="col-primary" />
              </Link>
            </div>
          </div>
          <div className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden">
            <Image
              src={"/royalvillas2.png"}
              alt="profile"
              fill
              sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
              priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
              className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
            />
            <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
              <Link
                href={"https://royal-villas-ramkumargurav.vercel.app"}
                className="text-xl text-white"
              >
                RoyalVillas.com
              </Link>
              <p className="text-sm text-white px-2 text-center ">
                It's an app related to hotel bookings where one can make advance
                reservations for rooms and also can buy villa party packages
                with payment interface
              </p>
              <Link
                href={"https://royal-villas-ramkumargurav.vercel.app"}
                className="rounded-full p-4 bg-white"
              >
                <GoLinkExternal size={25} className="col-primary" />
              </Link>
            </div>
          </div> */}
        </div>
      </section>
      <h2 className="rounded-md my-4 mx-10 py-4 pl-4 mt-10 text-xl font-semibold nunito uppercase  sm:text-[30px] text-white bg-[#8a8888]">
        {staticApps.length} Static Websites <br />
      </h2>
      <p className="pl-12 my-4 text-base text-white  sm:text-[20px]  ">
        {" "}
        Built their Frontend using Reactjs
      </p>
      <section className="mb-28">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 px-10 py-4 place-content-center place-items-center">
          {staticApps.map((app, i) => (
            <div
              key={i}
              className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden"
            >
              <Image
                src={`${app.image}`}
                alt="profile"
                fill
                sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
                priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
                className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
              />
              <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
                <Link href={`${app.link}`} className="text-xl text-white ">
                  {app.name}
                </Link>
                <p className="text-sm text-white px-2 text-center ">
                  {app.desc}
                </p>
                <Link
                  href={`${app.link}`}
                  className="rounded-full p-4 bg-white"
                >
                  <GoLinkExternal size={25} className="col-primary" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      <h2 className="rounded-md my-4 mx-10 py-4 pl-4 mt-10 text-xl font-semibold nunito uppercase  sm:text-[30px] text-white bg-[#8a8888]">
        {springbootApis.length} APIs <br />
      </h2>
      <p className="pl-12 my-4 text-base text-white  sm:text-[20px]  ">
        {" "}
        Built using Nodejs and Springboot framework
      </p>
      <section className="mb-28">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 px-10 py-4 place-content-center place-items-center">
          {springbootApis.map((app, i) => (
            <div
              key={i}
              className="card rounded-md  relative w-[300px] h-[300px] overflow-hidden"
            >
              <Image
                src={`${app.image}`}
                alt="profile"
                fill
                sizes="(max-width: 640px) 100vw
              (max-width: 1024px) 50vw,
              33vw" //thie is used when we use grid with cards images (this downloads small size imagees at bigger devices width and bigger images at smaller devices width to improve userexperience)
                priority //When true, the image will be considered high priority and preload. Lazy loading is automatically disabled for images using priority.
                className="rounded-md object-cover" //always give object-cover class to make image responsive without losing its aspects ratio( The image keeps its aspect ratio and fills the given dimension. The image will be clipped to fit)
              />
              <div className="absolute top-0 left-0 w-full h-full cgx-primary flex flex-col justify-center items-center gap-4 px-2">
                <Link href={`${app.link}`} className="text-xl text-white ">
                  {app.name}
                </Link>
                <p className="text-sm text-white px-2 text-center ">
                  {app.desc}
                </p>
                <Link
                  href={`${app.link}`}
                  className="rounded-full p-4 bg-white"
                >
                  <GoLinkExternal size={25} className="col-primary" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Projects;
